from app.schemas.nutrition import FoodItem
from app.schemas.social import Challenge
from app.schemas.workout import Exercise

EXERCISES: list[Exercise] = [
    Exercise(
        id="ex1",
        name="Barbell Bench Press",
        muscle_group="Chest",
        equipment="Barbell",
        difficulty="Intermediate",
        instructions="Lie on a flat bench, lower the bar to mid-chest, and press up explosively.",
        sets=4,
        reps="8-10",
        weight=80,
        rest_time=90,
    ),
    Exercise(
        id="ex2",
        name="Incline Dumbbell Press",
        muscle_group="Chest",
        equipment="Dumbbell",
        difficulty="Intermediate",
        instructions="Press dumbbells upward on a 30–45° incline bench with controlled motion.",
        sets=3,
        reps="10-12",
        weight=28,
        rest_time=75,
    ),
    Exercise(
        id="ex3",
        name="Cable Fly",
        muscle_group="Chest",
        equipment="Cable",
        difficulty="Beginner",
        instructions="Bring cable handles together in a wide arc, squeezing chest at the top.",
        sets=3,
        reps="12-15",
        weight=15,
        rest_time=60,
    ),
    Exercise(
        id="ex4",
        name="Push-Up",
        muscle_group="Chest",
        equipment="Bodyweight",
        difficulty="Beginner",
        instructions="Keep body straight, lower chest to floor, and press back up.",
        sets=3,
        reps="15-20",
        weight=0,
        rest_time=45,
    ),
    Exercise(
        id="ex5",
        name="Barbell Row",
        muscle_group="Back",
        equipment="Barbell",
        difficulty="Intermediate",
        instructions="Hinge at hips, pull bar to lower chest while keeping back flat.",
        sets=4,
        reps="8-10",
        weight=70,
        rest_time=90,
    ),
    Exercise(
        id="ex6",
        name="Lat Pulldown",
        muscle_group="Back",
        equipment="Cable",
        difficulty="Beginner",
        instructions="Pull bar to upper chest, squeezing lats at the bottom of the movement.",
        sets=3,
        reps="10-12",
        weight=55,
        rest_time=75,
    ),
    Exercise(
        id="ex7",
        name="Pull-Up",
        muscle_group="Back",
        equipment="Bodyweight",
        difficulty="Advanced",
        instructions="Pull chin above bar with full range of motion and controlled descent.",
        sets=3,
        reps="6-10",
        weight=0,
        rest_time=90,
    ),
    Exercise(
        id="ex8",
        name="Seated Cable Row",
        muscle_group="Back",
        equipment="Cable",
        difficulty="Beginner",
        instructions="Pull handle to torso, squeezing shoulder blades together at peak contraction.",
        sets=3,
        reps="10-12",
        weight=50,
        rest_time=75,
    ),
    Exercise(
        id="ex9",
        name="Barbell Overhead Press",
        muscle_group="Shoulders",
        equipment="Barbell",
        difficulty="Intermediate",
        instructions="Press bar overhead from shoulder height with tight core and glutes.",
        sets=4,
        reps="8-10",
        weight=50,
        rest_time=90,
    ),
    Exercise(
        id="ex10",
        name="Dumbbell Lateral Raise",
        muscle_group="Shoulders",
        equipment="Dumbbell",
        difficulty="Beginner",
        instructions="Raise dumbbells to shoulder height with a slight bend in elbows.",
        sets=3,
        reps="12-15",
        weight=10,
        rest_time=60,
    ),
    Exercise(
        id="ex11",
        name="Face Pull",
        muscle_group="Shoulders",
        equipment="Cable",
        difficulty="Beginner",
        instructions="Pull rope toward face, externally rotating shoulders at end range.",
        sets=3,
        reps="15-20",
        weight=20,
        rest_time=60,
    ),
    Exercise(
        id="ex12",
        name="Barbell Curl",
        muscle_group="Arms",
        equipment="Barbell",
        difficulty="Beginner",
        instructions="Curl barbell without swinging, keeping elbows pinned to sides.",
        sets=3,
        reps="10-12",
        weight=30,
        rest_time=60,
    ),
    Exercise(
        id="ex13",
        name="Dumbbell Hammer Curl",
        muscle_group="Arms",
        equipment="Dumbbell",
        difficulty="Beginner",
        instructions="Curl dumbbells with neutral grip, alternating or simultaneous.",
        sets=3,
        reps="10-12",
        weight=14,
        rest_time=60,
    ),
    Exercise(
        id="ex14",
        name="Tricep Pushdown",
        muscle_group="Arms",
        equipment="Cable",
        difficulty="Beginner",
        instructions="Extend elbows fully at bottom, keeping upper arms stationary.",
        sets=3,
        reps="12-15",
        weight=25,
        rest_time=60,
    ),
    Exercise(
        id="ex15",
        name="Barbell Back Squat",
        muscle_group="Legs",
        equipment="Barbell",
        difficulty="Intermediate",
        instructions="Squat to parallel or below, driving through mid-foot to stand.",
        sets=4,
        reps="6-8",
        weight=100,
        rest_time=120,
    ),
    Exercise(
        id="ex16",
        name="Leg Press",
        muscle_group="Legs",
        equipment="Machine",
        difficulty="Beginner",
        instructions="Lower platform with control, press through full foot without locking knees.",
        sets=3,
        reps="10-12",
        weight=140,
        rest_time=90,
    ),
    Exercise(
        id="ex17",
        name="Romanian Deadlift",
        muscle_group="Legs",
        equipment="Barbell",
        difficulty="Intermediate",
        instructions="Hinge at hips with slight knee bend, lowering bar along legs.",
        sets=3,
        reps="8-10",
        weight=80,
        rest_time=90,
    ),
    Exercise(
        id="ex18",
        name="Leg Curl",
        muscle_group="Legs",
        equipment="Machine",
        difficulty="Beginner",
        instructions="Curl heels toward glutes, pausing briefly at peak contraction.",
        sets=3,
        reps="12-15",
        weight=40,
        rest_time=60,
    ),
    Exercise(
        id="ex19",
        name="Calf Raise",
        muscle_group="Legs",
        equipment="Machine",
        difficulty="Beginner",
        instructions="Rise onto toes with full stretch at bottom and squeeze at top.",
        sets=4,
        reps="15-20",
        weight=60,
        rest_time=45,
    ),
    Exercise(
        id="ex20",
        name="Plank",
        muscle_group="Core",
        equipment="Bodyweight",
        difficulty="Beginner",
        instructions="Hold rigid plank position with neutral spine and engaged core.",
        sets=3,
        reps="45-60s",
        weight=0,
        rest_time=45,
    ),
    Exercise(
        id="ex21",
        name="Cable Crunch",
        muscle_group="Core",
        equipment="Cable",
        difficulty="Beginner",
        instructions="Crunch down by flexing spine, not pulling with arms.",
        sets=3,
        reps="15-20",
        weight=30,
        rest_time=45,
    ),
    Exercise(
        id="ex22",
        name="Deadlift",
        muscle_group="Back",
        equipment="Barbell",
        difficulty="Advanced",
        instructions="Drive floor away, keeping bar close to body throughout the lift.",
        sets=4,
        reps="5-6",
        weight=120,
        rest_time=120,
    ),
    Exercise(
        id="ex23",
        name="Hip Thrust",
        muscle_group="Legs",
        equipment="Barbell",
        difficulty="Intermediate",
        instructions="Drive hips up until torso is parallel to floor, squeezing glutes at top.",
        sets=3,
        reps="10-12",
        weight=80,
        rest_time=75,
    ),
    Exercise(
        id="ex24",
        name="Bulgarian Split Squat",
        muscle_group="Legs",
        equipment="Dumbbell",
        difficulty="Intermediate",
        instructions="Lower back knee toward floor with front foot flat, torso upright.",
        sets=3,
        reps="10-12",
        weight=20,
        rest_time=75,
    ),
]

FOODS: list[FoodItem] = [
    FoodItem(name="Chicken Breast", calories=165, protein=31, carbs=0, fats=3.6, portion="100g"),
    FoodItem(name="Brown Rice", calories=216, protein=5, carbs=45, fats=1.8, portion="1 cup cooked"),
    FoodItem(name="Greek Yogurt", calories=100, protein=17, carbs=6, fats=0.7, portion="170g"),
    FoodItem(name="Eggs (2 large)", calories=140, protein=12, carbs=1, fats=10, portion="2 eggs"),
    FoodItem(name="Oatmeal", calories=150, protein=5, carbs=27, fats=3, portion="40g dry"),
    FoodItem(name="Salmon Fillet", calories=206, protein=22, carbs=0, fats=13, portion="100g"),
    FoodItem(name="Sweet Potato", calories=112, protein=2, carbs=26, fats=0.1, portion="1 medium"),
    FoodItem(name="Banana", calories=105, protein=1.3, carbs=27, fats=0.4, portion="1 medium"),
    FoodItem(name="Whey Protein Shake", calories=120, protein=24, carbs=3, fats=1.5, portion="1 scoop"),
    FoodItem(name="Almonds", calories=164, protein=6, carbs=6, fats=14, portion="28g"),
    FoodItem(name="Avocado", calories=160, protein=2, carbs=9, fats=15, portion="1/2 fruit"),
    FoodItem(name="Whole Wheat Bread", calories=80, protein=4, carbs=14, fats=1, portion="1 slice"),
    FoodItem(name="Cottage Cheese", calories=98, protein=11, carbs=3.4, fats=4.3, portion="100g"),
    FoodItem(name="Broccoli", calories=55, protein=3.7, carbs=11, fats=0.6, portion="1 cup"),
    FoodItem(name="Apple", calories=95, protein=0.5, carbs=25, fats=0.3, portion="1 medium"),
    FoodItem(name="Peanut Butter", calories=188, protein=8, carbs=6, fats=16, portion="2 tbsp"),
    FoodItem(name="Tuna", calories=132, protein=28, carbs=0, fats=1.3, portion="100g canned"),
    FoodItem(name="Quinoa", calories=222, protein=8, carbs=39, fats=3.6, portion="1 cup cooked"),
    FoodItem(name="Olive Oil", calories=119, protein=0, carbs=0, fats=13.5, portion="1 tbsp"),
    FoodItem(name="Milk (2%)", calories=122, protein=8, carbs=12, fats=4.8, portion="1 cup"),
]

CHALLENGES: list[Challenge] = [
    Challenge(
        id="c1",
        name="30-Day Workout Challenge",
        description="Complete at least 20 workouts in 30 days",
        duration=30,
        progress=14,
        total=20,
        participants=2847,
        active=True,
        type="workout",
    ),
    Challenge(
        id="c2",
        name="10K Steps Daily",
        description="Walk 10,000 steps every day for 2 weeks",
        duration=14,
        progress=9,
        total=14,
        participants=5621,
        active=True,
        type="cardio",
    ),
    Challenge(
        id="c3",
        name="100K kg Volume Month",
        description="Lift a combined 100,000 kg this month",
        duration=30,
        progress=52000,
        total=100000,
        participants=1203,
        active=True,
        type="strength",
    ),
    Challenge(
        id="c4",
        name="Protein Goal Streak",
        description="Hit your daily protein target for 7 consecutive days",
        duration=7,
        progress=4,
        total=7,
        participants=3890,
        active=True,
        type="nutrition",
    ),
]

EXERCISE_BY_ID = {exercise.id: exercise for exercise in EXERCISES}
